import type { Metadata } from "next";
import { Great_Vibes } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Loading from "@/components/Loading";
import { LoadingProvider } from "@/contexts/LoadingContext";

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${greatVibes.className}`}>
        <LoadingProvider>
          <Header/>
          <Loading />
          <div>
            {children}
          </div>
          <Footer/>
          <ToastContainer
            limit={1}
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
          />
        </LoadingProvider>
      </body>
    </html>
  );
}